chore: Added rough draft of pieces OS page
pieces-app/documentation pull request #167
Opened 2023-10-23 17:45 UTC by mason-at-pieces

2023-10-24 15:34 UTC, jordan-pieces commented
@georgia-at-pieces can you take a pass at the copy here and review for us?

2023-10-24 15:46 UTC, jordan-pieces commented
@mason-at-pieces lets do a few things here: 

1. lets remove `pieces os` from **installation and getting started** in the sidebar 
2. then remove `desktop app` & `pieces os` from **apps & plugins**
3. change the name of `install & get started` to Installation
4. change the name of `overview` to getting started

![Screenshot 2023-10-24 at 11 36 02 AM](https://github.com/pieces-app/documentation/assets/55861512/29849c36-5e3a-4c24-9ee2-c79815e69115)

---

Now on the **Overview** page (which should now be named `Getting Started`):

1. Remove everything from `Bring order to the Chaos` to the bottom of the page, and replace it with your Pieces OS page content 

Let me know if you need any clarification here :) but i think this will make more sense and create a very consumable entry point into our documentation that is less confusing

2023-10-24 15:48 UTC, jordan-pieces requested changes
there are changes in the comments and see my one note in the code :)

2023-10-24 15:48 UTC, jordan-pieces commented on docs/installation-getting-started/pieces-os.mdx
> +### Installation Guide
if we do keep this section, we can probably just put the OS direct download links in each of these tabs for Pieces OS

2023-10-24 15:54 UTC, georgia-at-pieces approved these changes

2023-10-30 14:14 UTC, jordan-pieces approved these changes
looks great thanks for all of the updates!!

2023-10-30 14:14 UTC, merged