add cli docs
pieces-app/documentation pull request #498
Opened 2024-07-17 16:51 UTC by Bishoy-at-pieces

2024-07-17 18:20 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +title: Pieces for Developers CLI Tool
I think in general, just a look at proper formatting should be followed. 

Also we should add some assets - GIFs of using the CLI.

2024-07-17 18:20 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +##### Commiting to github
Github

2024-07-17 18:20 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +##### Commiting to github
Also you can keep the title as Auto Commit to GIthub

2024-07-17 18:22 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +Auto commit the code to github and generate a commit message you can use the `-p` or `--push` flags to push the code to the repo too.
I think this description should be updated. We should also add some additional details on how it works, ie.e looking at the git diff and then using that to give you a good looking commit message

2024-07-17 18:22 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +###### Coversations
"Coversations" should be "Conversations"

2024-07-17 18:22 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +pieces conversation -r My awsome name
"awsome" should be "awesome" in the conversation rename example

2024-07-17 18:23 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +The save create edit and delete commands currrently work on the current asset which is by defualt set to the most recent one and you can change the current asset to anything using the open command ab
currently

2024-07-17 18:23 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +title: Pieces for Developers CLI Tool
Also please remove the Inconsistent capitalization: sometimes you use "Pieces OS" and other times "Pieces os"

And you can remove all the typos / grammatical errors

2024-07-17 18:24 UTC, shivay-at-pieces requested changes

2024-07-17 18:24 UTC, shivay-at-pieces commented on docs/extensions-plugins/cli.mdx
> +title: Pieces for Developers CLI Tool
Also if you can follow the structure as recommended by @mason-at-pieces for other products

2024-07-17 22:27 UTC, cole-at-pieces commented
"Pieces CLI Tool" should be proper naming convention. We can still mention it's a Python CLI tool, but any proper noun should be our name for it.

2024-07-17 22:29 UTC, Bishoy-at-pieces commented
I think I will stick with Pieces CLI tool 
should I capitalize the "t" in tool?

2024-07-17 22:32 UTC, cole-at-pieces commented
> I think I will stick with Pieces CLI tool should I capitalize the "t" in tool?

Yes I'd do that

2024-07-17 22:41 UTC, Bishoy-at-pieces commented
Thank you @cole-at-pieces 
https://documentation-git-add-cli-agent-docs-pieces-for-developers.vercel.app/
check it and let me know if you have any other concerns 
everything should be to Pieces CLI Tool

2024-07-19 17:26 UTC, mason-at-pieces commented
@Bishoy-at-pieces lets make sure that we are using h2's for subheadings. Seems like we skipped from h1 straight to h3

2024-08-07 20:08 UTC, merged