feat: Add JupyterLab docs
pieces-app/documentation pull request #68
Opened 2023-06-20 21:34 UTC by mason-at-pieces

2023-06-21 14:31 UTC, jordan-pieces requested changes
just small stuff i caught when i took a peek - ill look again before final PR but keep us updated @mason-at-pieces

2023-06-21 14:31 UTC, jordan-pieces commented on docs/extensions-plugins-support/troubleshooting-jupyterlab.mdx
@mason-at-pieces you don't need this since the page did not exist previously, these are just redirects for when the pages exist already and may be cached by any users browsers

2023-06-21 14:31 UTC, jordan-pieces commented on docs/extensions-plugins-support/troubleshooting-obsidian.mdx
same here since obsidian was the first page to be created on the `/extensions-plugins/*` route

2023-06-21 15:39 UTC, mason-at-pieces commented on docs/extensions-plugins-support/troubleshooting-obsidian.mdx
10-4

2023-06-23 02:58 UTC, jordan-pieces approved these changes
looks great merging this now! thanks again

2023-06-23 02:58 UTC, jordan-pieces commented on docs/extensions-plugins/jupyterlab.mdx
> +  <TabItem value="pypi">
we can one line these later it will make it a little smoother and give a full width code block - but we can do it later no need for right now

2023-06-23 02:59 UTC, jordan-pieces commented on docs/extensions-plugins/jupyterlab.mdx
> +  <TabItem value="pypi">
i selected the wrong part of the code here @mason-at-pieces but ill tell you about it tomorrow

2023-06-23 02:59 UTC, merged